[settings]
quiet = true
task_output = "interleave"
experimental = true
aqua.registries = ["https://github.com/KnickKnackLabs/bats-core"]

[plugins]
shiv = "https://github.com/KnickKnackLabs/vfox-shiv"

[tools]
uv = "latest"
"aqua:KnickKnackLabs/bats-core" = "1.14.0-kkl.3"
"aqua:shenwei356/rush" = "0.7.0"
usage = "1"
jq = "latest"
gum = "0.17.0"
"shiv:codebase" = "0.4"
"shiv:readme" = "0.3"

[_.codebase]
name = "monkeys"
lint = ["@all"]
