#!/usr/bin/env bash
#MISE description="Format byte count as human-readable size"
#MISE hide=true
#USAGE arg "<bytes>" help="Number of bytes to format"

BYTES="${usage_bytes}"

if [[ $BYTES -ge 1048576 ]]; then
    echo "$(echo "scale=1; $BYTES / 1048576" | bc) MB"
elif [[ $BYTES -ge 1024 ]]; then
    echo "$(echo "scale=1; $BYTES / 1024" | bc) KB"
else
    echo "${BYTES} bytes"
fi
